import React from 'react'

const AppContext = React.createContext({
  addListToGroup: () => {},
  handleGroupSelection: () => {},
  setNewGroupName: () => {},
  createGroup: () => {},
  handleContactSelection: () => {},
  setNavBarToggle: () => {},
  swiped: () => {},
  outOfFrame: () => {},
  swipe: () => {},
  navAddGames: () => {},
  setLastDirection: () => {},
  setGames: () => {},
  loginUser: () => {},
  setEmail: () => {},
  setPassword: () => {},
  setName: () => {},
  setBGAName: () => {},
  setBGAListName: () => {},
  setBGAListID: () => {},
  getBGAUserLists: () => {},
  getBGAList: () => {},
  createAccount: () => {},
  onSubmitNewContact: () => {},
  setContactID: () => {},
  setContactName: () => {},
  getContacts: () => {},
  checkAuth: () => {},
  goToSwipeGroup: () => {},
  getGamesForSwiper: () => {},
  games: [],
  selectedContacts: [],
  userGroupData: [],
  lists: [],
  selectedList: '',
  groups: [],
  selectedGroup: '',
  user_id: '',
  contacts: [],
  user_name: '',
  BGAName: '',
  lastDirection: '',
  userName: '',
  userEmail: '',
  userPassword: '',
  isAuthenticated: false,
  navBarToggle: false
})

export default AppContext
