import React from "react";

const AppContext = React.createContext({
  addCollectionToGroup: () => {},
  handleGroupSelection: () => {},
  setNewGroupName: () => {},
  createGroup: () => {},
  handleContactSelection: () => {},
  setNavBarToggle: () => {},
  swiped: () => {},
  outOfFrame: () => {},
  swipe: () => {},
  navAddGames: () => {},
  setLastDirection: () => {},
  setGames: () => {},
  loginUser: () => {},
  setEmail: () => {},
  setPassword: () => {},
  setName: () => {},
  setBGGName: () => {},
  setCollectionName: () => {},
  setBGGUsername: () => {},
  getBGGCollection: () => {},
  createAccount: () => {},
  onSubmitNewContact: () => {},
  setContactID: () => {},
  setContactName: () => {},
  getContacts: () => {},
  checkAuth: () => {},
  goToSwipeGroup: () => {},
  getGamesForSwiper: () => {},
  onSubmitDeleteAccount: () => {},
  currentGame: "",
  matchedGames: [],
  games: [],
  selectedContacts: [],
  userGroupData: [],
  collections: [],
  selectedCollection: "",
  groups: [],
  selectedGroup: "",
  user_id: "",
  contacts: [],
  user_name: "",
  BGGName: "",
  lastDirection: "",
  userName: "",
  userEmail: "",
  userPassword: "",
  isAuthenticated: false,
  type: null,
  message: null,
  right: -40,
  navBarToggle: false,
});

export default AppContext;
